version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cad-py-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://caduser:cadpassword@postgres:5432/caddb
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./backend:/app
      - backend_logs:/app/logs
    depends_on:
      - postgres
      - redis
    networks:
      - cad-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: cad-py-postgres
    environment:
      - POSTGRES_DB=caddb
      - POSTGRES_USER=caduser
      - POSTGRES_PASSWORD=cadpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - cad-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: cad-py-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cad-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  nginx:
    image: nginx:alpine
    container_name: cad-py-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
    networks:
      - cad-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  backend_logs:
    driver: local

networks:
  cad-network:
    driver: bridge
